### PR TITLE
Gap fill code

### PR DESCRIPTION
**Pull request by Guillaumedemoff**
I created an addon for codemirror that allows to add editable areas (tags) in a template code. 
The CodeBlock component can get the value that are written in the areas.

Detailed features:
- multiline areas (usefull for bodies of functions)
- non-multiline areas (usefull to fill in ifs or loops conditions)
- navigate forward through the tags with Alt-Tab

### CODE REVIEW

**Comment by Guillaumedemoff** [comment]
I just added backward navigation through the tags with Shift-Tab

**Comment by combefis** [comment]
Thanks for the pull request.

There is an issue when I use the component on a task without the "options" field for a "sourceCode". Your code requires the field to be there, even if it is empty. Could you fix this?

**Comment by Guillaumedemoff** [comment]
OK, I'll make it optional.

**Comment by combefis** [comment]
I found another issue that you should check when parsing the configuration of the plugin. Here is the configuration I used:

```
"sourceCode": [{
   "language": "python",
   "template": "@@hello@@ world @@hello@@",
   "options": {
      "tags": {
         "hello": {
            "multiline": true
         }
      }
   }
}]
```
The first line in the editor becomes editable where it should not (close to both tags). Could you check this bug?

Also, you should check that the user does not specify two tags with the same name and produce an error if so. Could you also check this issue and propose a way to handle it?

**Comment by Guillaumedemoff** [comment]
Could you tell me how to reproduce the bug that you found?

Concerning the configuration, I'll show an alert instead of the editor if the it is not correct. Is that ok for you ?

**Comment by combefis** [comment]
> Could you tell me how to reproduce the bug that you found?

Using the component with the configuration I put before, I followed these steps:

1. Clicking in the right tag.
2. Entering some characters in the right tag.
3. Clicking just on the right of the left tag.
4. Starting to type.

It surprised me. Either the three dots have not been correctly removed, or it should forbid me to write there.

**Comment by combefis** [comment]
> Concerning the configuration, I'll show an alert instead of the editor if the it is not correct. Is that ok for you ?

OK with your proposition to handle malformed or wrong configuration. For example, you can just write "Malformed or wrong configuration" in red, or something like that.

**Comment by Guillaumedemoff** [comment]
OK, It was caused by the two tags with the same name. Therefore it will be corrected by checking the given configuration

**Comment by Guillaumedemoff** [comment]
I made the template and the options optional as discussed earlier. There is also a check of the configuration with an alert if it is not correct. I added a loading animation to wait for the template to be loaded and parsed

**Comment by Guillaumedemoff** [comment]
I found a new bug with the insert caret. It is not showing when you click on an empty tag and you previously where in a tag with some content.

I will add an e2e test and fix this issue

**Comment by combefis** [comment]
Perfect for the changes, they are working fine! Found another bug while continuing to test the plugin:

```
"sourceCode": [{
   "language": "python",
   "template": "@@a@@@@b@@",
   "options": {
      "tags": {
         "a": {
            "multiline": true
         }
      }
   }
}]
```

When I click on the right tag and start to edit it, the ellipsis of the left tag is disappearing.

**Comment by Guillaumedemoff** [comment]
I don't think that it make sense to have two tags in a row. For example, if you put "hello" in the first one and "world" in the second one, you will end up with "helloworld" in text. We can use juste one tag for that. What do you think ? Should we forbid that in the config ?

**Comment by combefis** [comment]
> What do you think ? Should we forbid that in the config ?

Good idea, adjacent tags can be forbidden and you can check it in the configuration.

**Comment by combefis** [comment]
Perfect!

Also, multiline tags should only be possible for tags alone on their own line, could you also check it in the configuration?

And there is still a bug with the caret not showing for a tag that is directly starting the line, when you click on it with the mouse (for example: `"template": "@@hello@@ ......"`), can you look at it?

**Comment by combefis** [comment]
There is an issue with the multiline config check, not working with the following example: `"template": "@@a@@ @@b@@"` with `a` single line and `b` multiline.

**Pull request merged**
